#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         mod_perl
version:      1.29
version_from: 
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_07
